# render.yaml
services:
  # A PostgreSQL database
  - name: official-voice-db
    type: pserv
    plan: free 
    psqlVersion: "14"
    
  # The Flask Web App
  - name: official-voice-app
    type: web
    runtime: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn --worker-class eventlet -w 1 app:app"
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.6
      - key: DATABASE_URL
        fromService:
          type: pserv
          name: official-voice-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true # Render will automatically generate a secret key
      - key: ADMIN_PASSWORD # Important! You still need to set this.
        value: YourSuperSecretAdminPassword123! # CHANGE THIS